version: "3"
services:
    gaia:
        build: .
        image: gaia-runner
        environment:
            - "GAIA_URL=http://localhost:8080"
            - "GAIA_RUNNER_API_PASSWORD=123456"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock